name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grab dependency
      run: apt update; apt install -y gfortran libopenblas-dev
    - name: Build
      run: cargo test --verbose
      working-directory: server
